name: school_diary
description: Школьный дневник с голосовым вводом и ИИ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Хранение данных на телефоне
  shared_preferences: ^2.2.2

  # HTTP запросы (для Gemini AI)
  http: ^1.1.0

  # Голосовой ввод
  speech_to_text: ^6.6.0

  # Иконки
  flutter_svg: ^2.0.9

  # Анимации
  flutter_animate: ^4.5.0

  # Красивые шрифты
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
